---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# rTorch.examples

<!-- badges: start -->
<!-- badges: end -->

The goal of `rTorch.examples` is to show practical examples developed with the package [rTorch](https://cran.r-project.org/web/packages/rTorch/index.html). The vignettes included here were initially part of `rTorch`, but I moved them to a sseparate package to speed up the proccess of building the more challenging and newer `rTorch`.

The examples, and vignettes, are simple applications of [PyTorch]() that I found in the web. Some of the examples are just straight forward scripts with few PyTorch calls and random generated datasets; other examples are more ellaborated and require the creation of classes, and access to relatively heavy datasets.



## Installation

You can install the released version of rTorch.examples from GitHub with:

``` r
devtools::install_github("f0nzie/rTorch.examples")
```

## Examples included

* Simple Linear Regression
* Linear Regregression, rainfall
* Linear Regregression, rainfall. PyTorch builtins
* Two Layer Neural Network
* Logistic Regression, MNIST digits
* MNIST digits recognition, IDX format
* MNIST digits recognition, PNG images
* MNIST Fashion images. Inference and Validation



## References

* GitHub repository of `rTorch`: https://github.com/f0nzie/rTorch
* Website for `rTorch`: https://f0nzie.github.io/rTorch/
* Website for `rTorch.examples`: https://f0nzie.github.io/rTorch.examples/
* Website for `PyTorch`: https://pytorch.org/


